In [8]:
import pandas as pd
df = pd.read_csv("batch_results.csv")
df.head()

,RunId,iteration,Step,width,height,seed,authority,authority_density,Mean Knowledge,Mean Behavior,Net Health Belief
0,3,0,0,50,50,0,False,0.25,-0.000249,0.5136,0.019852
1,3,0,1,50,50,0,False,0.25,0.001911,0.5204,0.020060
2,3,0,2,50,50,0,False,0.25,0.005071,0.5180,0.020255
3,3,0,3,50,50,0,False,0.25,0.011031,0.5168,0.020180
4,3,0,4,50,50,0,False,0.25,0.012511,0.5164,0.020409

In [16]:
df = df.drop(labels=["height", "width"], axis=1)

In [27]:
df_filtered = df[df["Step"] == 100]

In [18]:
df_filtered = df_filtered.sort_values(by="seed", ascending=False)

In [28]:
df_filtered = df_filtered[df_filtered["iteration"] == 1]

In [30]:
auth_only = df_filtered[df_filtered["authority"] == True]
auth_only = auth_only.sort_values(by="seed")

In [31]:
auth_only

,RunId,iteration,Step,seed,authority,authority_density,Mean Knowledge,Mean Behavior,Net Health Belief
6261,60,1,100,0,True,0.25,-1.548531,0.4564,-0.089261
6564,61,1,100,0,True,0.50,-1.674221,0.4748,-0.052800
7069,62,1,100,0,True,0.75,-1.104488,0.4692,-0.060366
6968,66,1,100,1,True,0.25,4.588006,0.5344,0.069211
7170,67,1,100,1,True,0.50,0.996695,0.5276,0.053120
7574,68,1,100,1,True,0.75,0.426331,0.5176,0.030444
7675,72,1,100,2,True,0.25,-0.205161,0.4944,-0.011400
7877,73,1,100,2,True,0.50,-4.512028,0.4428,-0.113075
8281,74,1,100,2,True,0.75,-3.308561,0.4332,-0.133342
8180,78,1,100,3,True,0.25,-11.489236,0.4312,-0.137304
8382,79,1,100,3,True,0.50,-1.408849,0.4812,-0.038243
8887,80,1,100,3,True,0.75,-0.801124,0.4740,-0.058869
8786,84,1,100,4,True,0.25,0.611830,0.5100,0.017085
8988,85,1,100,4,True,0.50,5.060486,0.5504,0.102949
9493,86,1,100,4,True,0.75,3.415167,0.5524,0.101638
10099,92,1,100,5,True,0.75,2.495053,0.5544,0.108447
9392,90,1,100,5,True,0.25,-6.727278,0.4556,-0.091549
9594,91,1,100,5,True,0.50,-0.166386,0.5008,0.005032
9897,96,1,100,6,True,0.25,-1.630369,0.4924,-0.017216
10200,97,1,100,6,True,0.50,1.998223,0.5200,0.045112
10705,98,1,100,6,True,0.75,2.433189,0.5580,0.111498
10503,102,1,100,7,True,0.25,-6.376067,0.4840,-0.029420
10806,103,1,100,7,True,0.50,1.004738,0.5104,0.019960
11311,104,1,100,7,True,0.75,0.775440,0.5024,0.005668
11109,108,1,100,8,True,0.25,5.124724,0.5184,0.038401
11412,109,1,100,8,True,0.50,4.710110,0.5456,0.084678
11816,110,1,100,8,True,0.75,4.691420,0.5520,0.108983
12018,115,1,100,9,True,0.50,-2.282642,0.4732,-0.054945
11917,114,1,100,9,True,0.25,-3.290181,0.4716,-0.055695
12523,116,1,100,9,True,0.75,-1.600597,0.4828,-0.033818

In [23]:
df_filtered[df_filtered["seed"] == 7]

,RunId,iteration,Step,seed,authority,authority_density,Mean Knowledge,Mean Behavior,Net Health Belief
16361,165,2,100,7,False,0.25,3.229870,0.5248,0.053710
10604,107,1,100,7,False,0.75,3.229870,0.5248,0.053710
16563,167,2,100,7,False,0.75,3.229870,0.5248,0.053710
22421,225,3,100,7,False,0.25,3.229870,0.5248,0.053710
10503,102,1,100,7,True,0.25,-6.376067,0.4840,-0.029420
10402,106,1,100,7,False,0.50,3.229870,0.5248,0.053710
16765,162,2,100,7,True,0.25,-6.376067,0.4840,-0.029420
16866,163,2,100,7,True,0.50,1.004738,0.5104,0.019960
16462,166,2,100,7,False,0.50,3.229870,0.5248,0.053710
10301,105,1,100,7,False,0.25,3.229870,0.5248,0.053710
11311,104,1,100,7,True,0.75,0.775440,0.5024,0.005668
17371,164,2,100,7,True,0.75,0.775440,0.5024,0.005668
10806,103,1,100,7,True,0.50,1.004738,0.5104,0.019960
22926,223,3,100,7,True,0.50,1.004738,0.5104,0.019960
23431,224,3,100,7,True,0.75,0.775440,0.5024,0.005668
22623,227,3,100,7,False,0.75,3.229870,0.5248,0.053710
4544,42,0,100,7,True,0.25,-6.376067,0.4840,-0.029420
28582,286,4,100,7,False,0.50,3.229870,0.5248,0.053710
4746,43,0,100,7,True,0.50,1.004738,0.5104,0.019960
5251,44,0,100,7,True,0.75,0.775440,0.5024,0.005668
28683,287,4,100,7,False,0.75,3.229870,0.5248,0.053710
28784,282,4,100,7,True,0.25,-6.376067,0.4840,-0.029420
22724,222,3,100,7,True,0.25,-6.376067,0.4840,-0.029420
22522,226,3,100,7,False,0.50,3.229870,0.5248,0.053710
4443,47,0,100,7,False,0.75,3.229870,0.5248,0.053710
29188,283,4,100,7,True,0.50,1.004738,0.5104,0.019960
29491,284,4,100,7,True,0.75,0.775440,0.5024,0.005668
4342,46,0,100,7,False,0.50,3.229870,0.5248,0.053710
4241,45,0,100,7,False,0.25,3.229870,0.5248,0.053710
28481,285,4,100,7,False,0.25,3.229870,0.5248,0.053710